//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int t_id { get; set; }
        public Nullable<int> t_amount { get; set; }
        public Nullable<int> a_id { get; set; }
        public string tt_type { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Transactiontype Transactiontype { get; set; }
    }
}
